### PR TITLE
fix client secret keyref value key in readme

### PR DESCRIPTION
**Pull request by psych0d0g**
### Description

Just an update to the readme to document the correct key names for existing clientsecret values from pre-existing secret

### CODE REVIEW

**Comment by psych0d0g** [comment]
I have read and understood the CLA and hereby agree to its terms by making this Pull Request Comment.

**Comment by amitlicht** [comment]
Thanks for your fix @psych0d0g!  🦦 
This also needs fixing in https://github.com/otterize/docs/blob/main/docs/reference/network-mapper/helm-chart.mdx, let me know if you'd like to take care of that or I will 🙏

**Comment by amitlicht** [comment]
@psych0d0g I noticed the failing E2E CI tests on your PR, they seem related to this issue https://github.com/dorny/test-reporter/issues/149. 
I'm on it.

**Comment by amitlicht** [comment]
@psych0d0g could you please pull the latest https://github.com/otterize/helm-charts main into your fork? Hopefully this commit: https://github.com/otterize/helm-charts/commit/9fc35a81d9ba1cb22cc8e4bf5d87b5e58b2436d9 solves the CI issues

**Comment by amitlicht** [comment]
I see it's still failing. I'll merge your PR despite the failures (it's only failing to report the test results, the tests themselves are fine), and will follow this up at a later time.

**Pull request merged**
