### PR TITLE
Add support for deploying the intents operator in host network, as well as setting a custom metrics port for it

### PR DESCRIPTION
**Pull request by remixtj**
### Description

When installing intents operator on AWS  EKS using calico cni, control plane doesn't have access to services hosted on EKS cluster. The only way to have webhook working is to set them to use hostNetwork. Port conflict with hostnetwork was happening, so the option to set metrics port has been added.

### Checklist

- [x] I have added documentation for new/changed functionality in this PR and in github.com/otterize/docs

### CODE REVIEW

**Comment by amitlicht** [comment]
@remixtj thank you for your contribution! we're working on validating it.

**Comment by amitlicht** [comment]
@remixtj Thanks again for your contribution. Having reviewed your PR, I have a number of follow-up questions: 
1. In your PR body, you referred to issues accessing webhook servers. However, in your PR content, you provided tooling for changing the metrics port (2112), not the webhooks port (typically 9443). And so, I'm confused about the exact nature of the bug you are trying to solve. 
2. Can you provide details for the setup in which you encounter this issue, of the control plane failing to access webhooks? Exact EKS & calico versions, as well as otterize-k8s version. Please provide as much information as possible to help us reproduce this issue and validate your solution for it. 
3. Have you tested this change on the same setup and managed to verify it indeed solves the issue? I'm particularly concerned about the network-mapper deployment, which works in a similar way, meaning it uses the same port, on pod-network, for its metrics server. I would expect the same issue to recur in the network-mapper.

**Comment by remixtj** [comment]
Just to add few infos. You may find in the log the following error when using the setup i told you before:

```
E1216 15:18:50.099473       1 reflector.go:147] k8s.io/client-go@v0.29.0/tools/cache/reflector.go:229: Failed to watch *v2alpha1.ClientIntents: failed to list *v2alpha1.ClientIntents: conversion webhook for k8s.otterize.com/v1beta1, Kind=ClientIntents failed: Post "https://intents-operator-webhook-service.otterize-system.svc:443/convert?timeout=30s": Address is not allowed
```

This can be solved only by using host networking.

Luca

**Comment by amitlicht** [comment]
@remixtj got it 👍 
In that case, please open a matching PR in https://github.com/otterize/docs, documenting the additional helm chart flags, under https://github.com/otterize/docs/blob/main/docs/reference/intents-operator/helm-chart.mdx

**Review by amitlicht — APPROVED** [review]

**Pull request merged**
